/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'reset-password': RouteRecordInfo<'reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'system-activity-logs': RouteRecordInfo<'system-activity-logs', '/system/activity-logs', Record<never, never>, Record<never, never>>,
    'system-organizations': RouteRecordInfo<'system-organizations', '/system/organizations', Record<never, never>, Record<never, never>>,
    'system-permissions': RouteRecordInfo<'system-permissions', '/system/permissions', Record<never, never>, Record<never, never>>,
    'system-roles': RouteRecordInfo<'system-roles', '/system/roles', Record<never, never>, Record<never, never>>,
    'system-settings': RouteRecordInfo<'system-settings', '/system/settings', Record<never, never>, Record<never, never>>,
    'system-settings-notification': RouteRecordInfo<'system-settings-notification', '/system/settings-notification', Record<never, never>, Record<never, never>>,
    'system-users': RouteRecordInfo<'system-users', '/system/users', Record<never, never>, Record<never, never>>,
    'task-assignment-departments': RouteRecordInfo<'task-assignment-departments', '/task-assignment/departments', Record<never, never>, Record<never, never>>,
    'task-assignment-documents': RouteRecordInfo<'task-assignment-documents', '/task-assignment/documents', Record<never, never>, Record<never, never>>,
    'task-assignment-item-types': RouteRecordInfo<'task-assignment-item-types', '/task-assignment/item-types', Record<never, never>, Record<never, never>>,
    'task-assignment-types': RouteRecordInfo<'task-assignment-types', '/task-assignment/types', Record<never, never>, Record<never, never>>,
  }
}
